trigger: 
  branches:
    include:
      - main

pool: 'agentpool'

stages:
  - stage: PipelineQualityGate
    displayName: Quality Gate
    jobs:
      - job: QualityGate
        displayName: QualityGate
        steps:
          - script: |
              echo "Cloning old repository..."
              git clone --mirror https://$(AZURE_USERNAME):$(AZURE_PAT)@dev.azure.com/ImmanuelSianturi/Project-Poc/_git/Project-Poc
              cd Project-Poc.git
              echo "Adding new repository as remote..."
              git remote add new-origin https://immanuel12:$(GITHUB_PAT)@github.com/immanuel12/mirror-repo.git
              echo "Pushing changes to new repository..."
              git push new-origin --mirror
            displayName: "Execute Git Mirror"
          
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '8.x'  # Sesuaikan dengan versi SDK .NET yang digunakan oleh proyek Anda

          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
              vstsFeed: '0e1c30e7-f4f0-4ed1-999a-ad562f081ada'
          
          - task: DotNetCoreCLI@2
            displayName: 'Run Unit Tests'
            inputs:
              command: 'test'
              projects: '**/*.csproj'
   
  - stage: PipelineQualityGate
    displayName: Quality Gate
    jobs:            
      - job: CI
        displayName: CI
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: |
                HelloWorldApp/HelloWorldApp.csproj
                HelloWorldApp.Tests/HelloWorldApp.Tests.csproj
              arguments: '--configuration Release'
          
          - task: DotNetCoreCLI@2
            displayName: 'Publish Project'
            inputs:
              command: 'publish'
              publishWebProjects: false # Change to true if this is a web project
              projects: '**/*.csproj'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          
          - task: DotNetCoreCLI@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '0e1c30e7-f4f0-4ed1-999a-ad562f081ada'