trigger:
  branches:
    include:
      - main  # Jalankan pipeline ketika ada perubahan di branch master
  
  paths:
    include:
    - project

pool: agentpool  # Menggunakan agen Ubuntu untuk menjalankan pipeline

variables:
  dockerRegistryServiceConnection: 'devops-poc'  # Service connection ke Docker Hub
  imageRepository: 'nuek21/app'  # Nama repository di Docker Hub
  containerRegistry: 'docker.io'
  tag: '$(Build.BuildId)'  # Menggunakan BuildId sebagai tag versi image

steps:
  # Langkah 1: Install dependencies dan jalankan tes pada aplikasi Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Versi Node.js yang akan digunakan (ubah sesuai kebutuhan)
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
    displayName: 'Install dependencies and run tests'

  # Langkah 2: Build Docker image
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        latest
        $(tag)

  # Langkah 3: Push Docker image ke Docker Hub
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'push'
      tags: |
        latest
        $(tag)
