trigger:
  branches:
    include:
      - main

stages:
  - stage: MirrorRepo
    displayName: Mirror Repository
    jobs:
      - job: MirrorJob
        displayName: Run Git Mirroring
        pool: 'Default'
        steps:
          - script: |
              echo "Cloning old repository..."
              git clone --mirror http://localhost/DefaultCollection/Project-Poc/_git/Project-Poc
              cd Project-Poc.git
              echo "Checking current remotes..."
              git remote -v
              echo "Removing old remote if exists..."
              git remote remove new-origin || true
              echo "Adding new repository as remote..."
              git remote add new-origin https://ImmanuelSianturi:$(AZURE_CLOUD_PAT)@dev.azure.com/ImmanuelSianturi/Project-Poc/_git/Project-Poc
              echo "Pushing changes to new repository..."
              git push new-origin --mirror
            displayName: "Execute Git Mirror"
