trigger:
  branches:
    include:
      - main

pool: 'agentpool'

steps:
  - task: mirror-git-repository-vsts-task@1
    inputs:
      sourceGitRepositoryUri: '$(Build.Repository.Uri)'
      sourceGitRepositoryPersonalAccessToken: '$(PATAZURE)'
      destinationGitRepositoryUri: 'https://github.com/immanuel12/mirror-repo.git'
      destinationGitRepositoryPersonalAccessToken: '$(PATGITHUB)'
