trigger: 
  branches:
    include:
      - main

stages:
  - stage: MirrorRepo
    displayName: Mirror Repository
    jobs:
      - job: MirrorJob
        displayName: Run Git Mirroring
        pool: 'agentpool'
        steps:
          - script: |
              echo "Cloning old repository..."
              git clone --mirror https://$(AZURE_USERNAME):$(AZURE_PAT)@dev.azure.com/ImmanuelSianturi/Project-Poc/_git/Project-Poc
              cd Project-Poc.git
              echo "Adding new repository as remote..."
              git remote add new-origin https://immanuel12:$(GITHUB_PAT)@github.com/immanuel12/mirror-repo.git
              echo "Pushing changes to new repository..."
              git push new-origin --mirror
            displayName: "Execute Git Mirror"