trigger: none

pool: agentpool  # Menggunakan agen Ubuntu yang dikelola oleh Microsoft

variables:
  dockerRegistryServiceConnection: 'devops-poc'  # Ganti dengan service connection ke Docker Hub
  imageRepository: 'nuek21/restore'  # Ganti dengan nama repository Docker Hub kamu
  tag: '$(Build.BuildId)'  # Menggunakan BuildId sebagai tag versi image
  containerName: 'node-app-restore'  # Nama container untuk menjalankan aplikasi 

steps:
  # Langkah 1: Checkout repository
  - checkout: self

  # Langkah 2: Install Node.js dependencies
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: npmAuthenticate@0
    inputs:
      workingFile: 'poc/.npmrc'

  # Langkah 3: Install dependencies dan build aplikasi
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'npm install myapp@1.0.1'
      customRegistry: 'useFeed'
      customFeed: '0e1c30e7-f4f0-4ed1-999a-ad562f081ada'

  - task: Npm@1
    inputs:
      command: 'publish'
      workingDir: 'poc'
      publishEndpoint: 'npmconn'
    displayName: 'Publish'

  # Langkah 4: Build Docker image dan push ke Docker Hub
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: 'poc/Dockerfile'  # Pastikan path ini sesuai
      tags: |
        latest
        $(tag)

  # Langkah 5: Jalankan container dengan port 3000
  - script: |
      docker run -d -p 3002:3002 --name $(containerName) $(imageRepository):$(tag)
    displayName: 'Run Docker Container on Port 3002'