trigger:
  branches:
    include:
      - main  # Jalankan pipeline ketika ada perubahan di branch main
  
  paths:
    include:
      - poc  # Hanya jalankan pipeline jika ada perubahan di folder poc

pool: agentpool  # Menggunakan agen Ubuntu yang dikelola oleh Microsoft

variables:
  dockerRegistryServiceConnection: 'devops-poc'  # Ganti dengan service connection ke Docker Hub
  imageRepository: 'nuek21/testing-node'  # Ganti dengan nama repository Docker Hub kamu
  tag: '$(Build.BuildId)'  # Menggunakan BuildId sebagai tag versi image
  containerName: 'node-app-container'  # Nama container untuk menjalankan aplikasi
  targetBranch: 'main'  # Branch target untuk pull request

steps:
  # Langkah 1: Checkout repository
  - checkout: self

  # Langkah 2: Install Node.js dependencies
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  # Langkah 3: Install dependencies dan build aplikasi
  - script: |
      cd poc  # Pindah ke direktori poc
      npm install  # Instal dependensi
      npm run build  # Jalankan build
    displayName: 'Install dependencies and Build application'

  # Langkah 4: Build Docker image dan push ke Docker Hub
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: 'poc/Dockerfile'  # Pastikan path ini sesuai
      tags: |
        latest
        $(tag)

  # Langkah 5: Jalankan container dengan port 3000
  - script: |
      docker run -d -p 3001:3001 --name $(containerName) $(imageRepository):$(tag)
    displayName: 'Run Docker Container on Port 3001'

  # Langkah 6: Menyimpan hasil build ke dalam artefak
  - script: |
      cd poc  # Pindah ke direktori poc untuk mengakses hasil build
      if [ -d "dist" ]; then  # Periksa apakah folder dist ada
          cp -r dist/* $(Build.ArtifactStagingDirectory)  # Salin hasil build ke direktori artefak
      fi
    displayName: 'Copy build output to artifacts'

  # Langkah 7: Publish artifacts
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish artifacts'
    artifact: drop